template/gnostr-syndicate:--list

diff --git a/template/gnostr-syndicate b/template/gnostr-syndicate
--- a/template/gnostr-syndicate
+++ b/template/gnostr-syndicate
@@ -4,6 +4,7 @@ help(){
 
 echo "USAGE:"
 echo    "gnostr-syndicate wss://e.nos.lol 1"
+echo    "gnostr-syndicate --list 1"
 exit;
 }
 
@@ -16,96 +17,68 @@ REPO=$(basename $some_path)
 PARENT_REPO=$(basename $(dirname $some_path))
 ##GRANDPARENT_REPO=$(basename $(dirname $(dirname $some_path)))
 
-
-
 IS_REPO=$(git rev-parse --is-inside-work-tree)
-#exit
-#echo $IS_REPO
 if $IS_REPO;then
-#echo 1 $IS_REPO=$REPO
 REPO=$(basename $some_path);
 else
-#echo 2 $IS_REPO=$REPO
 REPO=$(basename $(dirname $some_path));
 fi
 
 BRANCH=`git rev-parse --abbrev-ref HEAD` #&& echo $BRANCH
-
 GIT_ORIGIN=$(git config --get remote.origin.url)
-#echo $GIT_ORIGIN
-#exit;
 
 RELAY=${1:-wss://e.nos.lol}
-#echo $RELAY
 POW=${2:-1}
-#echo $POW
 GNOSTR_WEEBLE=$(gnostr-weeble)
 WEEBLE=${3:-$GNOSTR_WEEBLE}
-#echo $WEEBLE
 BLOCK=${4:-$(gnostr-blockheight)}
-#echo $BLOCK
 WOBBLE=${5:-$(gnostr-wobble)}
-#echo $WOBBLE
 count=0;
 new_count=0;
 INIT_COMMIT=$(git rev-list --all --max-parents=0)
-#echo $INIT_COMMIT;#exit
-##git log -1 --skip 2 --pretty=format:"%h"
-##git rev-parse --short=256 HEAD~2
-#exit
-## n=`printf '%016s' "$(git rev-parse --short=4 HEAD~2)"`
-#n=`printf '%064s' "$(git rev-parse HEAD~0)"`
-#echo $n
-## exit
 
-## branch=master
-## for commit in $(git rev-list $branch)
-## do
-##     ## if git ls-tree --name-only -r $commit | grep -q '\.hbm\.xml$'; then
-##     if git ls-tree --name-only -r $commit; then
-## 
-##         ##echo $commit
-##         exit 0
-##     fi
-## done
-## exit;
-
-## var=$((var+1))
-## ((var=var+1))
-## ((var+=1))
-## ((var++))
-
-#count=0
 for commit_hash in $(git rev-list $BRANCH);do
 
 padded_commit_hash=`printf '%064s' "$commit_hash"`
-#echo $padded_commit_hash
-#exit
-#echo $commit_hash
 count=$((count+1))
 done
-#exit
 export COUNT=$count
-#exit
 
-#new_count = 0
 for commit_hash in $(gnostr-reflog);do
+
 PARENT=$(git rev-parse $commit_hash^1)
-#echo $PARENT
-#echo $commit_hash
 padded_parent_hash=`printf '%064s' "$PARENT"`
-#echo padded_parent_hash=$padded_parent_hash
 padded_commit_hash=`printf '%064s' "$commit_hash"`
-#echo padded_commit_hash=$padded_commit_hash
 export NEW_COUNT=$new_count
-#n=`printf '%064s' "$(git rev-parse HEAD~$count)"`
-#echo $n
 PARENT_ID=$(gnostr --sec $padded_parent_hash | gnostr-xq .pubkey)
 ID=$(gnostr --sec $padded_commit_hash | gnostr-xq .pubkey)
 PARENT_ID=${PARENT_ID//\"/}
 ID=${ID//\"/}
-#echo PARENT_ID=$PARENT_ID
-#echo ID=$ID
+
+
+if [[ "$1" == "--list" ]];
+then
+for relays in $(gnostr-get-relays -s);
+do
+echo $relays
+gnostr --sec $padded_commit_hash \
+--pow $POW \
+-t gnostr \
+--tag repo $REPO \
+--tag relay $relays \
+--tag r $relays \
+--tag branch $BRANCH \
+--tag origin $GIT_ORIGIN \
+--tag weeble $WEEBLE \
+--tag block $BLOCK \
+--tag wobble $WOBBLE \
+-t $padded_commit_hash \
+--tag commit $commit_hash \
+--tag parent $PARENT \
+--tag p $PARENT_ID \
+--content "$(git show $commit_hash || exit)" | gnostr-post-event $relays || echo "$commit_hash failed!"
+done
+else
 gnostr --sec $padded_commit_hash \
 --pow $POW \
 -t gnostr \
@@ -121,18 +94,12 @@ gnostr --sec $padded_commit_hash \
 --tag commit $commit_hash \
 --tag parent $PARENT \
 --tag p $PARENT_ID \
---content "$(git show $commit_hash || exit)" | gnostr-post-event --relay $RELAY || echo "$commit_hash failed!"
-##echo $commit_hash;
-	#for commit_padded_hash in $(gnostr-reflog -p);do
-	##echo $commit_padded_hash;
-	#	gnostr --sec $commit_padded_hash --content "$(git show $commit_hash)"
-	#done
+--content "$(git show $commit_hash || exit)" | gnostr-post-event $RELAY || echo "$commit_hash failed!"
+fi
+
 if [[ "$commit_hash" == "$INIT_COMMIT" ]]; then
 exit;
 fi
 new_count=$((new_count+1))
-#echo $count & wait
-#echo $new_count & wait
-#exit
 done
 exit;
